CREATE USER adminDio WITH ENCRYPTED PASSWORD 'admin';
GRANT ALL PRIVILEGES ON DATABASE proiect TO adminDio;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO adminDio;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO adminDio;
